#!/usr/bin/env bash

# Colors
red="\033[0;31m"
green="\033[0;32m"

bold="\033[1m"

package='zypper'

is_installed () {
     which $1
}

install_via_package () {
    sudo package install -y $1
}

install () {
    if is_installed $1; then
        echo -e "$bold $1 $green- is installed!"
    else
        echo -e "Installing $bold $1 ..."
        install_via_package $1
    fi
}


############### ZSH ###############
# Install zsh
install zsh

# Install oh-my-zsh
[[ -d $HOME/.oh-my-zsh ]] || sh -c "$(wget -O- https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

# Install powerline fonts
install powerline
install fonts-powerline

# Install silver search
install silversearcher-ag

# Create symbolyc link for .zshrc config file
[[ -f $HOME/.zshrc ]] && mv $HOME/.zshrc $HOME/.zshrc.old
ln -s $HOME/.zsh/.zshrc $HOME/.zshrc

# Install fzf fuzzy finder
if [[ ! -d $HOME/.fzf ]]; then
     git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
     ~/.fzf/install --all
fi

# Load zsh
exec zsh -l

# Set zsh as default shell
sudo chsh -s $(which zsh)

echo -e "$bold $green Log out and login back again to use your new default shell."
